# Browser and Selenium setup
#selenium:
#  host: "localhost"
#  port: 4444

# Database environment settings
db_environment: 'name_of_db'

# URL configuration settings
base_url: "https://www.google.com/"
api_cart_url: "https://www.google.com/api"

# Screenshots settings
screenshots_path: "tmp/jenkins/screenshots"
screenshots_url: "tmp/jenkins/screenshots"

screenshots: "tmp/jenkins/screenshots"


resources:
  chrome:
    type: Website
    ip: localhost
    port: 4444
    browser: chrome

  firefox:
    type: Website
    ip: localhost
    port: 4444
    browser: firefox

  mysql:
    type: Database
    ip: 10.12.13.145
    user: username
    password: password
    port: 8888
    db: automation